INSERT INTO Mesa (ID, CODIGO) 
VALUES (1, '01');
INSERT INTO Mesa (ID, CODIGO) 
VALUES (2, '02');
INSERT INTO Mesa (ID, CODIGO) 
VALUES (3, '03');
INSERT INTO Mesa (ID, CODIGO) 
VALUES (4, '04');

INSERT INTO Reserva (
ID,FECHA_INICIO_RESERVA, FECHA_FIN_RESERVA,CANTIDAD_PERSONAS,TITULAR,JUEGO)
VALUES(1,NULL,NULL,4,'Jhoel','Exploding Kittens');

INSERT INTO Mesas_Por_Reserva (
ID, ID_MESA, ID_RESERVA)
VALUES(1,1,1);